export const HACKATHONS = [
  {
    id: "1",
    title: "هاكاثون بيت الشاورما",
    fields: "الذكاء الاصطناعي، التصميم، الشاورما",
    category: "الذكاء الاصطناعي",
    duration: "2 يوم",
    members: "1-4 أعضاء",
    prize: "3000",
    date: "19 يوليو",
    location: "عن بعد",
    featured: true,
  },
  ...[2, 3, 4, 5].map((n) => ({
    id: String(n),
    title: "مثال هاكاثون رقم واحد",
    fields: "الذكاء الاصطناعي، التصميم، الشاورما",
    category: "الذكاء الاصطناعي",
    duration: "2 يوم",
    members: "1-4 أعضاء",
    prize: "3000",
    date: "19 يوليو",
    location: "عن بعد",
    featured: false,
  })),
];

export const TEAM_ADS = [
  {
    id: "1",
    hackathonTitle: "هاكاثون 1",
    category: "الذكاء الاصطناعي",
    membersNeeded: "2",
    members: [
      { number: 1, gender: "", role: "", skills: "" },
      { number: 2, gender: "", role: "", skills: "" },
    ],
    date: "",
    location: "",
    prize: "",
    workDuration: "مدة العمل التقريبية :",
    attendance: "عن بعد \\ حضوري",
  },
  {
    id: "2",
    hackathonTitle: "هاكاثون 2",
    category: "الصحة",
    membersNeeded: "1",
    members: [{ number: 1, gender: "", role: "", skills: "" }],
    date: "",
    location: "",
    prize: "",
    workDuration: "مدة العمل التقريبية :",
    attendance: "عن بعد \\ حضوري",
  },
];